import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const out=path.dirname(fileURLToPath(import.meta.url));
const memo=fs.readFileSync(path.join(out,'memo.txt'),'utf8').replace(/\r/g,'').trim();
const chunks=memo.split(/\n-{20,}\n/).map(x=>x.trim());
const pages=[['index','Главная','Компетенция и основные принципы'],['service-check','Служебная проверка','Установить обстоятельства. Проверить доказательства. Принять мотивированное решение.'],['operative-check','Оперативная проверка','Основание проверки и полномочие на конкретное мероприятие проверяются отдельно.'],['powers','Полномочия','Для каждого действия — своё основание и условия применения.'],['discipline','Дисциплина','Взыскание — только в пределах полномочий конкретного сотрудника.'],['crime-sk','Преступление и СК','Пресечь угрозу. Сохранить доказательства. Соблюсти компетенцию.'],['algorithm','Алгоритм','От поступления информации до оформления решения.']];
const titles=['','Компетенция Управления «9»','Кого может проверять УП-9','Право на служебную проверку','Когда служебная проверка обязательна','Порядок и ограничения проверки','Объяснение сотрудника','Отказ от объяснения','Оперативная проверка и компетенция','Основания оперативной проверки','Перечень оперативных мероприятий','Опрос','Наведение справок','Исследование предметов и документов','Наблюдение','Телефон и переписка','Служебные базы','Запрос документов и сведений','Проверка документов','КПЗ и допросные','Закрытые территории','Режимные объекты','Обыск','Задержание','Наручники','Физическая сила','Специальные средства','Взыскания от УП-9','Виды взысканий','Кто вправе назначить взыскание','Как выбирать взыскание','Одно основное взыскание','Временное отстранение','Признаки преступления','До передачи материала СК','Передача материала и содействие СК','Алгоритм сотрудника УП-9'];
const route=n=>n<=2?'index':n<=7?'service-check':n<=15?'operative-check':n<=26?'powers':n<=32?'discipline':n<=35?'crime-sk':'algorithm';
const tags=n=>[7,15,29].includes(n)?['НЕЛЬЗЯ','danger']:[1,6,27].includes(n)?['МОЖНО','good']:[33,34,35].includes(n)?['СК','info']:[4,5,8,9,22,23].includes(n)?['НУЖНО ОСНОВАНИЕ','warn']:[28,31,36].includes(n)?['ВАЖНО','info']:['ТОЛЬКО ПРИ УСЛОВИИ','warn'];
const entries=chunks.filter(x=>/^\d+\. /u.test(x)).map(x=>{const i=x.indexOf('\n'),n=Number(x.slice(0,x.indexOf('.')));return {id:n,title:titles[n],originalTitle:x.slice(0,i),body:x.slice(i).trim(),page:route(n),tag:tags(n)}});
if(entries.length!==36)throw Error('Expected 36 sections, got '+entries.length);
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function prose(text){let mode='',html=''; for(const block of text.split(/\n\n+/)){const b=block.trim();if(!b)continue;if(/^(Правовое основание|Основание|Дополнительное основание|Правовое основание процедуры):$/i.test(b)){mode='basis';html+='<h3 class="eyebrow">ПРАВОВОЕ ОСНОВАНИЕ</h3>';continue;}if(/^(Что нельзя|Нельзя|Неправильно|Нельзя[^\n]*|Важно|Как действовать|Что можно|Пример|Как использовать|Практический порядок|Главное правило|Схема)[.:]?$/.test(b)){mode=/нельзя|неправильно/i.test(b)?'danger-text':/можно/.test(b)?'good-text':'';html+='<h3 class="'+mode+'">'+esc(b.replace(/:$/,''))+'</h3>';continue;}let cls=mode; if(/ст\.\s*\d|Глава V/.test(b))cls+=' law'; if(/запрещ|не является признанием|≠|не означает автомат|не должна подменять/.test(b))cls+=' caution';html+=b.startsWith('- ')?'<ul class="'+cls+'">'+b.split('\n').map(l=>'<li>'+esc(l.replace(/^- /,''))+'</li>').join('')+'</ul>':'<p class="'+cls+'">'+esc(b).replace(/\n/g,'<br>')+'</p>';if(mode==='basis')mode='';}return html;}
const link=n=>route(n)+'.html#section-'+n;
function card(e){return '<details class="article" id="section-'+e.id+'"><summary><span class="number">'+String(e.id).padStart(2,'0')+'</span><span class="summary-title">'+esc(e.title)+'</span><span class="badge '+e.tag[1]+'">'+e.tag[0]+'</span><span class="plus" aria-hidden="true">+</span></summary><div class="article-body">'+prose(e.body)+'</div></details>';}
const quick=[[1,'Компетенция УП-9'],[3,'Служебная проверка'],[6,'Объяснение сотрудника'],[8,'Оперативная проверка'],[11,'Опрос и справки'],[15,'Телефон и переписка'],[16,'Служебные базы'],[20,'Закрытые территории'],[22,'Обыск'],[23,'Задержание'],[24,'Наручники и сила'],[27,'Дисциплинарные взыскания'],[32,'Временное отстранение'],[33,'Преступление и СК'],[36,'Алгоритм']];
const answers=[
['телефон','телефон переписк discord telegram сообщен компьютер','НЕЛЬЗЯ требовать доступ только из-за статуса УП-9.','Ст. 37 ФЗ «О Федеральной службе безопасности РО». Ограничение защищённых прав требует судебного решения, если федеральный закон прямо не предусматривает другой специальный порядок. Процессуальный кодекс РО также требует судебного разрешения либо иной прямо предусмотренной законом формы для получения компьютерной информации, ограничивающего тайну сообщений.',15],
['обыск','обыск обыскать','НУЖНО отдельное законное основание.','Глава V Процессуального кодекса РО. Личный обыск без согласия допускается при задержании, аресте, исполнении судебного или другого предусмотренного законом процессуального акта либо в иных прямо установленных Кодексом случаях.',22],
['задержание','задерж задержать','НЕЛЬЗЯ задерживать «пока разберёмся» без законного основания.','Ч. 2 ст. 66 ФЗ «О Федеральной службе безопасности РО»: до передачи уголовного материала задержание возможно при наличии законных оснований.',23],
['наручники','наручник сил спецсредств','ТОЛЬКО при процессуальной необходимости.','Ст. 6.3 Процессуального кодекса РО: законное задержание, привод или иная мера процессуального принуждения. Не для наказания, унижения или только из-за спора. Физическая сила и специальные средства имеют отдельные условия применения.',24],
['документы','документ удостоверен','НУЖНО различать запрос сведений и проверку документов.','Ст. 44 ФЗ «О Федеральной службе безопасности РО»: конкретный и соразмерный запрос в пределах законной задачи и права на получение сведений. Проверка удостоверения личности регулируется отдельно — ст. 45 этого закона.',17],
['объяснение','объяснен отказ','МОЖНО запросить объяснение. Отказ не означает признания вины.','Ст. 22 Внутреннего устава Федеральной службы безопасности РО. До взыскания устанавливаются обстоятельства и запрашивается объяснение; отказ фиксируется. Проверка может продолжаться по имеющимся материалам.',6],
['базы','баз пробить пробив систем','ТОЛЬКО для законной служебной задачи.','Ст. 43 ФЗ «О Федеральной службе безопасности РО»: в пределах предоставленного доступа, при служебной необходимости и законной цели. Использование из любопытства, личного конфликта или для личной выгоды запрещено.',16],
['КПЗ','кпз допросн','МОЖНО при наличии предусмотренной законом служебной цели.','Ст. 2.7 ФЗ «О статусе территорий и особых объектах РО». Двигаться к месту назначения кратчайшим доступным путём. Доступ не даёт автоматического права на обыск, задержание, допрос или изъятие.',19],
['закрытая территория','закрыт территор режимн','ТОЛЬКО при законных основаниях.','Ст. 2.18 ФЗ «О статусе территорий и особых объектах РО». При сомнениях объяснить причину нахождения; точные сведения об объекте ОРМ сообщаются исключительно руководству организации. Для режимного объекта — ст. 3.16 этого закона.',20],
['взыскание','взыскан дисциплин наказан','МОЖНО только в пределах личной компетенции.','Ч. 5 ст. 23 Внутреннего устава Федеральной службы безопасности РО. До взыскания установить обстоятельства, запросить объяснение и мотивировать решение. За один проступок — одно основное взыскание.',27],
['увольнение','увольнен уволить понижен','НЕЛЬЗЯ считать, что любой сотрудник УП-9 вправе уволить.','Ст. 23 Внутреннего устава Федеральной службы безопасности РО разграничивает полномочия. Если права на меру нет, материал направляется уполномоченному лицу. При неочевидных или оспариваемых обстоятельствах до понижения либо увольнения проводится служебная проверка — ч. 1 ст. 16 ФЗ «О государственной службе РО».',29],
['отстранение','отстран','ВАЖНО: отстранение — обеспечительная мера, не взыскание.','Ст. 17 ФЗ «О государственной службе РО»: существенный риск для проверки, имущества, участников или иной существенный служебный риск. Полномочие конкретного сотрудника должно следовать из его компетенции либо приказа Директора.',32],
['СК','ск преступлен следствен','Служебная проверка не заменяет уголовное расследование.','Ст. 66 и ч. 3 ст. 77 ФЗ «О Федеральной службе безопасности РО». При достаточных данных о преступлении сотрудника ФСБ и конфликте интересов материал передаётся СК в предусмотренных уголовным законодательством случаях. После принятия материала УП-9 не подменяет следователя.',35]
];
const shortTitles=pages.map(p=>[p[0],p[1]]);
fs.writeFileSync(out+'/data.js','window.MEMO = '+JSON.stringify({entries,answers,pages:shortTitles},null,2)+';\n');
const glossary='<details class="glossary"><summary>Названия нормативных актов и сокращения</summary><p>ФЗ «О ФСБ РО» — Федеральный закон «О Федеральной службе безопасности РО». Внутренний устав ФСБ РО — Внутренний устав Федеральной службы безопасности РО.</p><p>Также в памятке: Федеральный закон «О государственной службе РО»; Федеральный закон «О статусе территорий и особых объектах РО»; Процессуальный кодекс РО.</p><p>ОРМ — оперативно-розыскные мероприятия. СК — Следственный комитет.</p></details>';
const search='<section class="search-panel" aria-label="Поиск по памятке"><label for="search">Найти основание или действие</label><div class="search-row"><span aria-hidden="true">⌕</span><input type="search" id="search" placeholder="Например, задержание или ст. 66" autocomplete="off"><button id="clear-search" type="button" aria-label="Очистить поиск">Сбросить</button></div><p id="search-status" role="status" class="muted">По всем 36 разделам, статьям и нормативным актам</p><div id="search-results" hidden></div></section>';
const quickAnswer='<section class="quick-answer"><div class="section-heading"><h2>Быстрый ответ</h2><span class="muted">По вашей ситуации</span></div><label for="question" class="sr-only">Вопрос по памятке</label><input id="question" placeholder="Можно ли посмотреть телефон?" type="search"><div class="chips">'+answers.map(a=>'<button type="button" data-question="'+esc(a[0])+'">'+esc(a[0])+'</button>').join('')+'</div><div id="answer" aria-live="polite"></div></section>';
for(const [slug,title,desc] of pages){let content='';if(slug==='index'){content='<section class="hero"><div><p class="eyebrow">RUSSIA ONLINE · СЛУЖЕБНАЯ ПАМЯТКА</p><h1>Памятка сотрудника<br>Управления «9»</h1><p class="subtitle">Собственная безопасность ФСБ РО</p></div><div class="hero-index" aria-hidden="true">09<span>УПРАВЛЕНИЕ</span></div></section><div class="principle"><span>01 <b>Сначала основание</b></span><i>→</i><span>02 <b>Потом действие</b></span><i>→</i><span>03 <b>Оформление результата</b></span></div><p class="intro">Сам факт принадлежности к Управлению «9» не даёт права применять любое действие по своему усмотрению. Для каждого серьёзного действия должно существовать отдельное законное основание.</p>'+search+quickAnswer+'<section><div class="section-heading"><h2>Быстрый доступ</h2><span class="muted">15 тем</span></div><div class="quick-grid">'+quick.map(([n,t],i)=>'<a class="quick-card" href="'+link(n)+'"><span class="number">'+String(i+1).padStart(2,'0')+'</span><strong>'+esc(t)+'</strong><span aria-hidden="true">↗</span></a>').join('')+'</div></section><section><div class="section-heading"><h2>Компетенция УП-9</h2><span class="muted">Основа работы</span></div>'+glossary+entries.filter(e=>e.page===slug).map(card).join('')+'</section>';}
else{content='<p class="eyebrow">УПРАВЛЕНИЕ «9» / ПАМЯТКА</p><h1>'+title+'</h1><p class="subtitle">'+desc+'</p>'+search+glossary;
if(slug==='algorithm'){const e=entries.find(e=>e.id===36);const parts=e.body.split(/\n\n↓\n\n/);content+='<section id="section-36" class="flow"><h2>'+esc(parts.shift())+'</h2>'+parts.map((p,i)=>{let lines=p.split('\n\n');let heading=lines.shift().replace(/^\d+\. /,'');return '<article class="step"><span class="step-number">'+String(i+1).padStart(2,'0')+'</span><div><h2>'+esc(heading.toLocaleLowerCase('ru').replace(/^./,s=>s.toUpperCase()))+'</h2>'+prose(lines.join('\n\n'))+'</div></article>';}).join('')+'</section><section class="main-rule"><h2>Главное правило УП-9</h2>'+prose(chunks.at(-1).replace(/^ГЛАВНОЕ ПРАВИЛО УП-9\n+/,''))+'</section>';}
else{content+='<div class="section-heading"><h2>Материалы раздела</h2><button class="text-button" id="expand-all">Раскрыть всё</button></div>'+entries.filter(e=>e.page===slug).map(card).join('');if(slug==='service-check')content+='<div class="related"><h2>Сбор материалов</h2><a href="powers.html#section-16">Служебные системы — ст. 43 →</a><a href="powers.html#section-17">Запрос документов и сведений — ст. 44 →</a></div>';if(slug==='operative-check')content+='<div class="notice">Конкретные ОРМ выполняют только уполномоченные подразделения и сотрудники — в пределах компетенции и установленной процедуры.</div>';}}
const html='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Рабочая памятка Управления 9 для игрового проекта Russia Online. Основания, полномочия и ограничения."><title>'+title+' · Управление «9»</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><script src="data.js" defer></script><script src="app.js" defer></script></head><body><a class="skip" href="#main">К содержанию</a><header><div class="header-inner"><a class="brand" href="index.html" aria-label="Управление 9 — главная"><span class="brand-mark">9</span><span>УПРАВЛЕНИЕ «9»<small>Собственная безопасность</small></span></a><button id="menu-toggle" aria-expanded="false" aria-controls="navigation">Меню <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Главное меню">'+pages.map(p=>'<a href="'+p[0]+'.html"'+(p[0]===slug?' aria-current="page"':'')+'>'+p[1]+'</a>').join('')+'</nav></div></header><main id="main" tabindex="-1">'+content+'</main><footer><span>УПРАВЛЕНИЕ «9» <b>/</b> RUSSIA ONLINE</span><p>Игровая нормативная база Russia Online. Содержание — из предоставленной памятки.</p><a href="memo.txt">Полный исходный текст ↗</a></footer><noscript><p class="notice">Материалы доступны без JavaScript. Для поиска и быстрых ответов включите JavaScript.</p></noscript></body></html>';
fs.writeFileSync(out+'/'+slug+'.html',html);}
fs.writeFileSync(out+'/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#132b48"/><text x="32" y="47" text-anchor="middle" font-family="sans-serif" font-size="46" font-weight="700" fill="#a8ccff">9</text></svg>');
fs.writeFileSync(out+'/.nojekyll','');
fs.writeFileSync(out+'/content.json',JSON.stringify({entries,answers},null,2));
console.log('Created '+entries.length+' complete sections and '+pages.length+' pages in '+out);
