import {normalize,linkReferences,basisHtml,warning} from './legal-bases.mjs';
import {cardAnswers} from './card-answers.mjs';
import {icon} from './visuals.mjs';
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export function readingBlocks(e){
 const legal='<section class="answer-block blue"><span class="block-icon">'+icon('scales')+'</span><div><h3>Правовое основание</h3>'+basisHtml(e.id)+'</div></section>';
 if([19,20,21].includes(e.id))return '<div class="answer-stack"><section class="answer-block amber"><span class="block-icon">!</span><div><h3>Основание не подтверждено</h3><p>'+warning+'</p></div></section>'+legal+'</div>';
 if(e.id===36)return legal;
 const answer=cardAnswers[e.id]?.map(t=>normalize(t,e.id));if(!answer)return '';
 const basis=[...new Set(e.body.split(/\n\n+/).filter(s=>/ст\.\s*\d|Глава V/.test(s)&&s.length<500))];
 const no=[];const chunks=e.body.split(/\n\n+/);for(let i=0;i<chunks.length;i++){if(/^(Нельзя|Что нельзя|Неправильно|Важно)/.test(chunks[i])&&chunks[i].length<80){let j=i+1;let text=[];while(j<chunks.length&&text.join(' ').length<550){if(/^(Основание|Правовое|Как |Пример|Схема)/.test(chunks[j]))break;text.push(chunks[j++]);if(text.at(-1).startsWith('- '))break;}if(text.length)no.push(text.join('\n'));}}
 const special={4:{yes:'Проводить служебную проверку и устанавливать обстоятельства предполагаемого нарушения.',when:'Если обстоятельства неочевидны или оспариваются сотрудником — до понижения или увольнения.',how:'Проверить, существовал ли приказ, был ли он законным, получил ли его сотрудник, мог ли выполнить и почему не выполнил. Установить вину и подтверждающие материалы.',no:'Нельзя считать жалобу доказанной виной и сразу назначать тяжёлое взыскание.'},3:{yes:'Проводить служебные проверки в пределах компетенции Управления «9».',when:'До понижения или увольнения, если обстоятельства неочевидны либо оспариваются сотрудником.',how:'Установить обстоятельства, дать сотруднику возможность объясниться и представить доказательства. Принять мотивированное решение.',no:'Служебная проверка не даёт автоматического права на задержание, обыск или доступ к переписке.'},6:{how:'Установить обстоятельства → предложить объяснение и материалы защиты → при отказе зафиксировать его.',no:'Нельзя заранее объявлять сотрудника виновным и требовать признания.'},7:{how:'Предложили объяснение → получили отказ → зафиксировали его → оцениваем остальные доказательства.',no:'Отказ от объяснения нельзя считать признанием вины.'}}[e.id]||{};
 const section=(tone,symbol,title,text)=>text?'<section class="answer-block '+tone+'"><span class="block-icon">'+icon(symbol)+'</span><div><h3>'+title+'</h3><p>'+linkReferences(escape(text)).replaceAll('\n','<br>')+'</p></div></section>':'';
 return '<div class="answer-stack">'+section(e.id===15?'red':'green',e.id===15?'cross':'check',e.id===15?'Что нельзя':'Что можно',special.yes||answer[0])+legal+section('amber','clock','Когда можно / что требуется',special.when||answer[1])+section('purple','gear','Как действовать',special.how)+section('red','cross','Что нельзя',special.no||no.join('\n'))+'</div>';
}
