import {normalize,linkReferences,basisHtml,basisMap,references,warning,label} from './legal-bases.mjs';
import {icon,topicIcons,building} from './visuals.mjs';
import {readingBlocks} from './reading-blocks.mjs';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.dirname(fileURLToPath(import.meta.url));
const old=JSON.parse(fs.readFileSync(root+'/source-memo.json','utf8'));
// Original memo, not forum overrides. Keep all source paragraphs and article numbers.
const entries=old.entries.map(({id,title,body,originalTitle})=>({id,title,body:normalize(body,id),originalTitle}));

const topics=[
['service-check','Служебная проверка','Проведение, объяснения, сбор материалов, запрос документов и др.','▤',[[4,'Когда проводится'],[3,'Право на проверку'],[5,'Как проводить и собирать материалы'],[6,'Объяснение сотрудника'],[7,'Отказ от объяснения'],[17,'Запрос документов'],[16,'Служебные системы']]],
['operative-check','Оперативная проверка','Основания, опрос, документы, наблюдение, телефон, компьютерная информация и др.','⌕',[[8,'Право и ограничения'],[9,'Основания'],[10,'Перечень ОРМ'],[11,'Опрос'],[12,'Наведение справок'],[13,'Исследование документов'],[14,'Наблюдение'],[15,'Телефон и компьютерная информация']]],
['powers','Полномочия','Служебные базы, документы, КПЗ, объекты, обыск, задержание, спецсредства и др.','◇',[16,17,18,19,20,21,22,23,24,25,26]],
['discipline','Дисциплина','Виды взысканий, кто может применять, выбор взыскания, отстранение.','⚖',[27,28,29,30,31,32]],
['crime-sk','Преступление и СК','Признаки преступления, действия до передачи, передача в СК.','§',[33,34,[35,'Передача и действия после принятия СК']]],
['algorithm','Алгоритм','Пошаговый порядок действий от получения информации до оформления результата.','↳',[36]],
['employees','Работа с сотрудниками','Объяснение, отказ от объяснения, права сотрудника.','♧',[1,2,6,7,4,32]],
['documents','Документы и материалы','Сбор, исследование, хранение и запрос сведений.','▱',[5,13,17,34]],
['restricted','Режим и режимные объекты','КПЗ, допросные, закрытые территории, режимные объекты.','▣',[19,20,21]],
['resources','Информационные ресурсы','Служебные базы, компьютерная информация, ограничения.','▰',[16,15,13,17]],
['risks','Запреты и риски','Что нельзя делать, типовые нарушения полномочий и ограничения.','!',[1,5,8,15,16,22,23,24,29,31,32,35]]
].map(([slug,title,description,icon,items],i)=>({slug,title,description,icon:icon,number:String(i+1).padStart(2,'0'),items:items.map(x=>Array.isArray(x)?{id:x[0],label:x[1]}:{id:x,label:entries.find(e=>e.id===x).title})}));
topics.forEach((t,i)=>t.icon=icon(topicIcons[i]));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const primary=id=>topics.find(t=>t.items.some(x=>x.id===id));
const keywords={15:'телефон Discord Telegram переписка компьютерная информация',16:'базы пробить',19:'КПЗ допросные',24:'наручники',29:'увольнение уволить',32:'отстранение',35:'СК следственный комитет'};
const data={entries:entries.map(e=>({...e,body:([19,20,21].includes(e.id)?warning+"\n\n":"")+e.body,topic:primary(e.id).slug,keywords:keywords[e.id]||''})),topics};
data.searchBases=Object.fromEntries(Object.entries(basisMap).map(([id,keys])=>[id,keys.map(k=>{const [key,unit]=k.split(':');const r=references[key];return {act:r.act,article:r.article,label:label(key,unit)};})]));
fs.writeFileSync(root+'/data.js','window.MEMO='+JSON.stringify(data)+';');
fs.writeFileSync(root+'/content.json',JSON.stringify(data,null,2));
function block(body){return body.startsWith('- ')?'<ul>'+body.split('\n').map(x=>'<li>'+linkReferences(esc(x.replace(/^- /,'')))+'</li>').join('')+'</ul>':'<p>'+linkReferences(esc(body)).replaceAll('\n','<br>')+'</p>';}
function material(e){
 if(e.id===36){return '<div class="steps">'+e.body.split(/\n\n↓\n\n/).map((x,i)=>'<section class="step"><span>'+String(i).padStart(2,'0')+'</span><div>'+x.split(/\n\n+/).map(block).join('')+'</div></section>').join('')+'</div><section class="meaning amber"><h3>4 главных вопроса</h3><ol><li>Что произошло?</li><li>Почему это относится к компетенции УП-9?</li><li>Какая конкретная статья разрешает это действие?</li><li>Выполнены ли условия её применения?</li></ol></section>';}
 let groups=[],current={title:'Подробная памятка',tone:'neutral',blocks:[]};
 for(const b of e.body.split(/\n\n+/)){
  const clean=b.trim();if(!clean)continue;
  const heading=/^(Правовое основание|Дополнительное основание|Основание|Предусмотрено|Правовое основание процедуры|Что можно|Как действовать|Практический порядок|Схема|Что нельзя|Нельзя|Нельзя пробивать|Нельзя задерживать|Нельзя использовать наручники|Неправильно|Важно|Главное правило|Пример|Как использовать|Простыми словами)[.:]?$/i;
  if(heading.test(clean)){if(current.blocks.length)groups.push(current);const title=clean.replace(/[.:]$/,'');current={title,tone:/основан|Предусмотрено/.test(title)?'blue':/Нельзя|Неправильно|Что нельзя/.test(title)?'red':/Важно|Главное правило/.test(title)?'amber':/Что можно/.test(title)?'green':'neutral',blocks:[]};}
  else current.blocks.push(clean);
 }
 if(current.blocks.length)groups.push(current);
 return groups.map(g=>'<section class="meaning '+g.tone+'"><h3><span aria-hidden="true">'+({blue:'⚖',red:'×',amber:'!',green:'✓',neutral:'·'}[g.tone])+'</span> '+esc(g.title)+'</h3>'+g.blocks.map(block).join('')+'</section>').join('');
}
function search(){return '<section class="search-area" aria-label="Поиск по памятке"><label for="search">Найти действие, статью или правило</label><div class="search-box"><span aria-hidden="true">⌕</span><input id="search" type="text" inputmode="search" placeholder="Например: телефон, ст 66, КПЗ…" autocomplete="off"><button id="clear-search" aria-label="Очистить поиск" type="button">×</button></div><p id="search-status" role="status">По всем темам и тексту памятки</p><div id="search-results" hidden></div></section>';}
function shell(title,body,slug=''){return '<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Игровая памятка УП-9 Russia Online: основания, действия, ограничения."><title>'+esc(title)+' · УП-9</title><link rel="icon" href="favicon.svg"><link rel="stylesheet" href="style.css?v=search-20260925"><script defer src="data.js?v=search-20260925"></script><script defer src="app.js?v=search-20260925"></script></head><body><a class="skip" href="#main">К содержанию</a><header><div class="topbar"><a class="brand" href="index.html"><span class="emblem">'+icon('shield')+'</span><span>УПРАВЛЕНИЕ «9»<small>Собственная безопасность ФСБ РО</small></span></a><button id="menu-toggle" aria-expanded="false" aria-controls="navigation">Меню ☰</button><nav id="navigation" aria-label="Основная навигация"><a href="index.html"'+(!slug?' aria-current="page"':'')+'>Главная</a>'+topics.slice(0,6).map(t=>'<a href="'+t.slug+'.html"'+(t.slug===slug?' aria-current="page"':'')+'>'+t.title+'</a>').join('')+'</nav></div></header><main id="main">'+body+'</main><footer>УПРАВЛЕНИЕ «9» <span> / </span> RUSSIA ONLINE<p>Игровая памятка. Не сайт государственного органа. Основания сверены с форумом Кутузовского 25.09.2026. Три ссылки о территориях требуют проверки и отмечены в соответствующих разделах.</p></footer><noscript><p class="nojs">Для поиска включите JavaScript. Все материалы доступны ниже.</p></noscript></body></html>';}
const home='<section class="hero"><div class="hero-art" aria-hidden="true">'+building+'</div><p class="eyebrow">RUSSIA ONLINE / СЛУЖЕБНАЯ ПАМЯТКА</p><h1>Памятка сотрудника<br>Управления «9»</h1><p class="subtitle">Собственная безопасность ФСБ РО</p><div class="principle">Сначала основание <b>→</b> потом действие <b>→</b> потом оформление результата</div></section>'+search()+'<section aria-labelledby="topics-heading"><div class="section-head"><h2 id="topics-heading">Выберите тему</h2><span>11 разделов</span></div><div class="topic-grid">'+topics.map(t=>'<a class="topic-card" href="'+t.slug+'.html"><div class="card-top"><span class="icon" aria-hidden="true">'+t.icon+'</span><span>'+t.number+'</span></div><h3>'+t.title+'</h3><p>'+t.description+'</p><span class="arrow" aria-hidden="true">↗</span></a>').join('')+'</div></section><section class="intro-note"><h2>Полномочие начинается с основания</h2><p>Сам факт принадлежности к Управлению «9» не позволяет применять любое действие по своему усмотрению.</p><a href="employees.html#section-1">Компетенция Управления «9» →</a></section>';
fs.writeFileSync(root+'/index.html',shell('Памятка сотрудника Управления «9»',home));
for(const t of topics){const body='<div class="breadcrumbs"><a href="index.html">Главная</a><span>›</span>'+t.title+'</div><div class="topic-heading"><a class="back" href="index.html" aria-label="Назад к темам">←</a><div><h1><span class="icon" aria-hidden="true">'+t.icon+'</span> '+t.title+'</h1><p class="subtitle">'+t.description+'</p></div></div>'+search()+'<div class="workspace"><aside><label for="subsection-select">Подраздел</label><select id="subsection-select">'+t.items.map(x=>'<option value="section-'+x.id+'">'+esc(x.label)+'</option>').join('')+'</select><nav class="subsections" aria-label="Подразделы">'+t.items.map(x=>'<a href="#section-'+x.id+'" data-section="section-'+x.id+'"><span class="side-icon">'+icon('document')+'</span>'+esc(x.label)+'<b>›</b></a>').join('')+'</nav></aside><div class="reading">'+t.items.map(x=>{const e=entries.find(e=>e.id===x.id);return '<article class="material" id="section-'+e.id+'" tabindex="-1"><div class="article-heading"><span class="icon" aria-hidden="true">'+icon('document')+'</span><h2>'+esc(x.label)+'</h2></div>'+readingBlocks(e)+(e.id===36?material(e):'<details class="full-text"><summary>'+([19,20,21].includes(e.id)?'Исходная памятка — основание не подтверждено':'Полный текст и подробности')+'</summary>'+material(e)+'</details>')+'</article>';}).join('')+'</div></div>';
fs.writeFileSync(root+'/'+t.slug+'.html',shell(t.title,body,t.slug));}
fs.writeFileSync(root+'/LEGAL-AUDIT.json',JSON.stringify({date:'2026-09-25',server:'Кутузовский',method:'Открыты и прочитаны пять первоисточников форума; zakon-RO- использован как индекс.',references,basisMap,unconfirmed:['t2.7','t2.18','t3.16'],note:'Единица подсчёта: уникальная статья НПА; повторные ссылки и части не считаются отдельными статьями. Внутренний устав назван по заголовку темы, совпадающему с src индекса. Статьи 6.1 и 6.3 Кодекса не имеют отдельного заголовка; название не придумано. Глава V уточнена до статьи 1 по прямому совпадению текста личного обыска.'},null,2));
console.log('Built 11 topics and 36 source sections');
